### ISSUE TITLE
Dropdown ui element doesnt work 

### ISSUE THREAD

**Issue by dpggit** [ViveSoftware/ViveInputUtility-Unity#159]
In a clean Unity 2018.3.13f1 project with just SteamVR 2.4.5 and VIU 1.10.6 dropdown doesnt work properly, i need to click several times in an option of the dropdown list so that is selected

**Comment by chengnay** [comment]
@dpggit Taking VIU example scene, 1.UGUI.
There are two methods to prevent trigger with no action.
1. Adjust the drag threshold to a larger value
![image](https://user-images.githubusercontent.com/33050705/68009108-00dc4e80-fcbc-11e9-8c39-94c5b6ff9a92.png)
2.  Adjust the duration of Pose Easer to a larger value,
![image](https://user-images.githubusercontent.com/33050705/68009170-3719ce00-fcbc-11e9-8818-22bdb88014b7.png)

The main reason is that dropdown list contains the scrollrect,
when user presses on the trigger button, the pointer tends to move a little bit, which makes scrollrect to get the action instead of toggle button.

**Comment by dpggit** [comment]
It works thanks

**Comment by dpggit** [comment]
It works but i have the problem Dropdown jitters as i move the pointer on the dropdown, how can i fix it?

**Comment by dpggit** [comment]
I found how, just set scroll type to none
