### ISSUE TITLE
Seems that the input does not work with OpenVR XR plugin

### ISSUE THREAD

**Issue by amidofu** [ViveSoftware/ViveInputUtility-Unity#208]
I checked OpenVR XR plugin [here](https://github.com/ValveSoftware/unity-xr-plugin) which you can download the unity package [here](https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/installer), the hmd and controller tracking can work but the button input can't. Anything I missed?

**Comment by chengnay** [comment]
@amidofu To get input, you are required to import SteamVR Unity Plugin.
Unity XR(OpenVR XR Plugin) can only use rendering.

**Comment by amidofu** [comment]
Is this the SteamVR plugin I should use? It makes Unity to enter an **infinite importing process** with this window keeps showing. I'm not sure if it is because I want to put WaveXR plugin, OpenVR XR plugin and VIU in the same project
![image](https://user-images.githubusercontent.com/1356094/99474931-6e6f2180-2988-11eb-857d-3e2c29fda4e6.png)

**Comment by chengnay** [comment]
@amidofu This is the one that you should import.
The infinite import process is because SteamVR Plugin has its own check to install OpenVR XR plugin automatically, but there is bug that makes it fall into infinite loop, but I am not sure why.
Could you close your Unity and delete the SteamVR plugin and try again? Or try removing OpenVR XR plugin?

**Comment by amidofu** [comment]
@chengnay OK, it seems the infinite importing process is caused by SteamVR plugin, thanks
