### ISSUE TITLE
Swapped input using HTC Vive

### ISSUE THREAD

**Issue by JerryLetehen** [ViveSoftware/ViveInputUtility-Unity#95]
Steps:
1. Create an empty project
2. Import  VIve Input Utility (v.1.10.3) and SteamVR Plugin (v.2.2.0) from Assets Store
3. Apply all recommends settings SteamVR/Vive Input Utility
4. Create an empty scene, delete MainCamera
5. Drag the ViveCameraRig prefab into created scene
6. Run the scene
7. Turn on both HTC Vive controllers
8. Turn off one of them
9. Swap controllers in your hands
10. Turn on the controller

Factual:  All inputs from controller in right hand trigger left controller, All inputs from controller in left hand trigger right controller. But their positions and rotations are correct.

Expected: All inputs from controller in left hand trigger left controller. The same with controller in right hand.

Video is [here](https://youtu.be/z6ICd2RBrio)

**Comment by wirelessdreamer** [comment]
@any HTC devs. correct me if i'm wrong: VIU tracks controllers by serial number, and intentionally trys to make sure controllers don't magically swap roles during run time. Wouldn't the above behavior be the expected behaviour. That as long as a controller with a role is on, it won't be reasigned a new role. 

On that same topic, if you set a viveRole in the binding, it won't change that role guaranteed.

**Comment by ani-rudh** [comment]
Hi guys,

I faced this problem when using the UGUI sample scene of VUI. All I did was to remove the mirroring of the contoller actions using the steramvr input tool. That did the trick.

Hope this is of some help.

BR,
Ani

**Comment by chengnay** [comment]
Latest VIU (1.10.4) package fixed this issue, please try it out. Thanks!
